service_account_path: /Users/thomas/Documents/projects/away_backend/auth/serviceAccountKey.json

grpc_server:
  port: 9000

redis:
  url: 127.0.0.1:42069

db:
  username: root
  password: secret
  ip_address: 127.0.0.1
  pool_max_conns: 10
  port: 5432

elastic:
  url: https://localhost:9200