// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	UserID         string    `json:"user_id"`
	PropertyID     uuid.UUID `json:"property_id"`
	BookingDate    time.Time `json:"booking_date"`
	AdditionalInfo *string   `json:"additional_info"`
}

type FeaturedArea struct {
	ID        int32   `json:"id"`
	Title     string  `json:"title"`
	PhotoUrl  string  `json:"photo_url"`
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
	Country   string  `json:"country"`
}

type Property struct {
	ID                  uuid.UUID `json:"id"`
	UserID              string    `json:"user_id"`
	PropertyTypeID      int16     `json:"property_type_id"`
	PropertyCategoryID  int16     `json:"property_category_id"`
	PropertyUsageID     int16     `json:"property_usage_id"`
	Bedrooms            int16     `json:"bedrooms"`
	Bathrooms           int16     `json:"bathrooms"`
	Surburb             *string   `json:"surburb"`
	Town                *string   `json:"town"`
	Title               string    `json:"title"`
	PDescription        *string   `json:"p_description"`
	Currency            string    `json:"currency"`
	Available           bool      `json:"available"`
	Price               float32   `json:"price"`
	Deposit             float32   `json:"deposit"`
	SharingPrice        *float32  `json:"sharing_price"`
	Promoted            bool      `json:"promoted"`
	PostedDate          time.Time `json:"posted_date"`
	PetsAllowed         bool      `json:"pets_allowed"`
	FreeWifi            bool      `json:"free_wifi"`
	WaterIncluded       bool      `json:"water_included"`
	ElectricityIncluded bool      `json:"electricity_included"`
	Latitude            float32   `json:"latitude"`
	Longitude           float32   `json:"longitude"`
}

type PropertyCategory struct {
	ID                  int16   `json:"id"`
	PCategory           string  `json:"p_category"`
	CategoryDescription *string `json:"category_description"`
}

type PropertyCombination struct {
	TypeID     int16 `json:"type_id"`
	CategoryID int16 `json:"category_id"`
}

type PropertyPhoto struct {
	ID         uuid.UUID `json:"id"`
	PropertyID uuid.UUID `json:"property_id"`
	PUrl       string    `json:"p_url"`
}

type PropertyReport struct {
	ReporterUserID     string    `json:"reporter_user_id"`
	ReportedPropertyID uuid.UUID `json:"reported_property_id"`
	Createdat          time.Time `json:"createdat"`
	RReason            string    `json:"r_reason"`
}

type PropertyReportReason struct {
	RReason      string `json:"r_reason"`
	RDescription string `json:"r_description"`
}

type PropertyType struct {
	ID              int16   `json:"id"`
	PType           string  `json:"p_type"`
	TypeDescription *string `json:"type_description"`
}

type PropertyUsage struct {
	ID               int16   `json:"id"`
	PUsage           string  `json:"p_usage"`
	UsageDescription *string `json:"usage_description"`
}

type Subscription struct {
	UserID  string `json:"user_id"`
	SStatus string `json:"s_status"`
}

type SubscriptionStatus struct {
	SStatus      string `json:"s_status"`
	SDescription string `json:"s_description"`
}

type User struct {
	ID                string    `json:"id"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	DeviceToken       string    `json:"device_token"`
	Bio               string    `json:"bio"`
	Verified          bool      `json:"verified"`
	SStatus           string    `json:"s_status"`
	ProfilePictureUrl string    `json:"profile_picture_url"`
	Createdat         time.Time `json:"createdat"`
}

type UserReport struct {
	ReporterUserID string    `json:"reporter_user_id"`
	ReportedUserID string    `json:"reported_user_id"`
	Createdat      time.Time `json:"createdat"`
	RReason        string    `json:"r_reason"`
}

type UserReportReason struct {
	RReason      string `json:"r_reason"`
	RDescription string `json:"r_description"`
}

type UserVerification struct {
	UserID    string         `json:"user_id"`
	Createdat time.Time      `json:"createdat"`
	FileUrls  sql.NullString `json:"file_urls"`
	VStage    string         `json:"v_stage"`
}

type VerificationStage struct {
	VStage       string `json:"v_stage"`
	VDescription string `json:"v_description"`
}
